
/* Action Types
 * List of all actions used by action creators
 */

export const FETCH_TOKEN = 'FETCH_TOKEN'
export const FETCH_TOKEN_SUCCESS = 'FETCH_TOKEN_SUCCESS'
export const FETCH_TOKEN_FAILURE = 'FETCH_TOKEN_FAILURE'

export const FETCH_DOMAINS = 'FETCH_DOMAINS'
export const FETCH_DOMAINS_SUCCESS = 'FETCH_DOMAINS_SUCCESS'
export const FETCH_DOMAINS_FAILURE = 'FETCH_DOMAINS_FAILURE'

export const FETCH_ALIASES = 'FETCH_ALIASES'
export const FETCH_ALIASES_SUCCESS = 'FETCH_ALIASES_SUCCESS'
export const FETCH_ALIASES_FAILURE = 'FETCH_ALIASES_FAILURE'

export const FETCH_ALIAS = 'FETCH_ALIAS'
export const FETCH_ALIAS_SUCCESS = 'FETCH_ALIAS_SUCCESS'
export const FETCH_ALIAS_FAILURE = 'FETCH_ALIAS_FAILURE'

export const CREATE_OUTGOING = 'CREATE_OUTGOING'
export const CREATE_OUTGOING_SUCCESS = 'CREATE_OUTGOING_SUCCESS'
export const CREATE_OUTGOING_FAILURE = 'CREATE_OUTGOING_FAILURE'

export const DELETE_OUTGOING = 'DELETE_OUTGOING'
export const DELETE_OUTGOING_SUCCESS = 'DELETE_OUTGOING_SUCCESS'
export const DELETE_OUTGOING_FAILURE = 'DELETE_OUTGOING_FAILURE'
